[gateway_microservice]
url="http://gateway:8000"

[users_microservice]
url="http://users:8000"
database_url="postgresql://users:users@users-pg:5432/users"

[stores_microservice]
url="http://stores:8000"
database_url="postgresql://stores:stores@stores-pg:5432/stores"

[orders_microservice]
url="http://orders:8000"
database_url="postgresql://orders:orders@orders-pg:5432/orders"

[billing_microservice]
url="http://billing:8000"
database_url="postgresql://billing:billing@billing-pg:5432/billing"

[saga_microservice]
url="http://saga:8000"

[warehouses_microservice]
url="http://warehouses:8000"
database_url="postgresql://warehouses:warehouses@warehouses-pg:5432/warehouses"

[notifications_microservice]
url="http://notifications:8000"
database_url="postgresql://notifications:notifications@notifications-pg:5432/notifications"

[delivery_microservice]
url="http://delivery:8000"
database_url="postgresql://delivery:delivery@delivery-pg:5432/delivery"